include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v22.0.0

variables:
#  AUTO_DEVOPS_TEST_DISABLED: "ðŸ›‘"
  AUTO_DEVOPS_QUALITY_DISABLED: "ðŸ›‘"
  AUTO_DEVOPS_KANIKO: "ðŸ›‘"
  AUTO_DEVOPS_ENABLE_KAPP: "ðŸ›‘"
  AUTO_DEVOPS_RELEASE_AUTO: "ðŸš€"
  AUTO_DEVOPS_PRODUCTION_AUTO: "ðŸš€"

Install:
  rules:
    - when: never

Build:
  rules:
    - when: never

Register Kaniko image:
  extends: .autodevops_register_kaniko_image
  needs: []
  variables:
    CONTEXT: ./index
    IMAGE_NAME: recherche-entreprises-index

Register API image:
  extends: .autodevops_register_kaniko_image
  needs: []
  variables:
    CONTEXT: ./api
    IMAGE_NAME: recherche-entreprises-api


.indexing_job:
  stage: Deploy
  extends:
    - .base_deploy_kosko_stage
  allow_failure: true

Download and Index (dev):
  extends:
    - .indexing_job
  rules:
    - if: "$CI_COMMIT_TAG"
      when: never
    - when: manual
  variables:
    KOSKO_GENERATE_ARGS: --env dev jobs/indexing
  environment:
    name: ${CI_COMMIT_REF_NAME}${AUTO_DEVOPS_DEV_ENVIRONMENT_NAME}
    url: https://${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}

Download and Index (prod):
  extends:
    - .indexing_job
  rules:
    - if: "$CI_COMMIT_TAG"
      when: manual
  variables:
    # the preprod env is used for production index
    # so it runs on the dev cluster
    KOSKO_GENERATE_ARGS: --env preprod jobs/indexing
  environment:
    name: preprod${AUTO_DEVOPS_PREPROD_ENVIRONMENT_NAME}
    url: https://preprod-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
